name: dispusip
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_root_jailbreak: ^2.0.2
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  jwt_decoder: ^2.0.1
  package_info_plus: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  uses-material-design: true
